# **Exercises**

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

In [2]:
rng = np.random.default_rng(seed = 42) # create a rand num generator

1. **How likely is it that you roll doubles when rolling two dice?**

- There is a 17.12% chance of rolling a double.

In [3]:
doubles = rng.choice([1, 2, 3, 4, 5, 6], (10_000, 2))
doubles

array([[1, 5],
       [4, 3],
       [3, 6],
       ...,
       [5, 1],
       [1, 3],
       [3, 3]])

In [4]:
doubles[:, 0] # isolate column one by index slicing; returns 1st column

array([1, 4, 3, ..., 5, 1, 3])

In [5]:
doubles[:, 1] # could have used axis sum

array([5, 3, 6, ..., 1, 3, 3])

In [6]:
(doubles[:, 1] == doubles[:, 0]).sum() # used .sum() method to returns all doubles

1712

In [7]:
rolled_double = (doubles[:, 1] == doubles[:, 0]).sum() # assigned variable to all doubles
rolled_double

1712

In [8]:
rolled_double/len(doubles)

0.1712

2. **If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?**

- 22.01% probability of flipping 8 coins and getting exactly 3 heads
- 63.98% probability of flipping 8 coins and getting more than 3 heads

In [9]:
flips = rng.choice([0, 1], (10_000, 8))
flips[:5]

array([[0, 1, 0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 1, 1, 0],
       [1, 1, 1, 1, 0, 0, 1, 1]])

In [10]:
flips_sum = flips.sum(axis = 1)
flips_sum[:5]

array([3, 2, 3, 2, 6])

In [11]:
flips_sum == 3

array([ True, False,  True, ..., False, False, False])

In [12]:
(flips_sum == 3).sum()

2201

In [13]:
exactly_threes = (flips_sum == 3).sum()
exactly_threes / len(flips_sum)

0.2201

In [14]:
more_than_three = (flips_sum > 3).sum()
more_than_three / len(flips_sum)

0.6398

3. **There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?**

 - 5.93% probability of both billdboard

In [15]:
billboard_choices = rng.choice([1, 2, 3, 4], (10_000, 2))
billboard_choices

array([[3, 4],
       [3, 2],
       [1, 3],
       ...,
       [4, 1],
       [2, 2],
       [1, 1]])

In [16]:
ds_cohort = ((billboard_choices[:, 0] + billboard_choices[:, 1]) == 2).sum()
ds_cohort / len(billboard_choices)

0.0593

4. **Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values**

- 72.42% probabililty there will be a chance of purchasing poptarts

In [17]:
cs = rng.normal(3, 1.5, (10_000, 5))
cs_eaten = cs.sum(axis = 1)
cs_eaten

array([18.31330061, 19.10886171, 11.99871834, ..., 18.30014292,
       12.25388303, 15.28656197])

In [18]:
poptarts_likely = (cs_eaten < 17).sum()
poptarts_likely/ len(cs_eaten)

0.7316

5. **Compare Heights**

    - Men have an average height of 178 cm and standard deviation of 8cm.

In [19]:
men = rng.normal(178, 8, 10_000)
men

array([169.03543562, 194.977672  , 185.70411888, ..., 164.32626887,
       183.54573869, 175.93092674])

    - Women have a mean of 170, sd = 6cm.

In [20]:
women = rng.normal(170, 6, 10_000)
women

array([166.52810302, 165.63609514, 157.33937377, ..., 175.64615129,
       162.20300757, 172.96271607])

    - Since you have means and standard deviations, you can use np.random.normal to generate observations.

    - If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [21]:
women > men

array([False, False, False, ...,  True, False, False])

In [22]:
women_taller = (women > men).sum()
women_taller / len(women)

0.21

6. **When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?**

- 50 students w/o corruption = 82.26%
- 100 sudents w/o corruption = 66.76%

In [23]:
corruption_chance = 1/250
corruption_chance

0.004

In [24]:
 fifty_failed = (rng.random((10_000, 50)) > corruption_chance).prod(axis=1).mean()

In [25]:
fifty_failed

0.8183

In [26]:
 one_hundred_failed = (rng.random((10_000, 100)) > corruption_chance).prod(axis=1).mean()

In [27]:
one_hundred_failed

0.6736

- **What is the probability that we observe an installation issue within the first 150 students that download anaconda?**

- 45.47% chance of failure

In [28]:
# subtract the result from 1 to get the proportion of rows with a successful installation (no corruption)
one_hundred_fifty = 1 - (rng.random((10_000, 150)) > corruption_chance).prod(axis=1).mean()

In [29]:
one_hundred_fifty

0.45609999999999995

- **How likely is it that 450 students all download anaconda without an issue?**

- 16.64% chance without corruption

In [30]:
four_hundred_fifty = (rng.random((10_000, 450)) > corruption_chance).prod(axis=1).mean()

In [31]:
four_hundred_fifty

0.1617

7. **There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?**

- 2.65% chance of no truck appearing is unlikely

In [32]:
three_days = (rng.random((10_000, 3)) > .7).prod(axis=1).mean()
three_days

0.0274

- **How likely is it that a food truck will show up sometime this week?**
- There is a 8.37% chance of a food truck will appear sometime this week.

In [33]:
week = (rng.random((10_000, 7)) <= .7).prod(axis=1).mean()
week

0.0828

8. **If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?**

    - 51.09% odds that two of them share birthday
    - 40.85% odds that two of them share birthday
    - 89.35% odds that two of them share birthday

In [34]:
bday_23 = rng.integers(1, 366, (10_000, 23))
bday_23 = pd.DataFrame(bday_23)
bday_23.head()

0    1    2    3    4    5    6    7    8    9   ...   13   14   15   16  \
0  184  336  152  233   20  156  126  125  192  332  ...   86  121   16  255   
1   85  286   82  266  312  132  211   39   32   18  ...  297   52  295  203   
2   24  154  205  154   16   76   51  288  232  282  ...  296  266  237   69   
3  161  142  170  149   65   35  257   76  265  102  ...   20  276  118  141   
4    5  256   50  147  332  229  232  252   14   79  ...  112  289    5  164   

    17   18   19   20   21   22  
0  197  358   96  117  126  257  
1  315  357  290  210  321   48  
2    2  243   41    9  171  142  
3  209  331  142  130  165   62  
4  243   45  335   40   97  134  

[5 rows x 23 columns]

In [35]:
share_bday_23 = (bday_23.nunique(axis=1) < 23).sum()

In [36]:
share_bday_23 / len(bday_23)

0.5102

In [37]:
bday_20 = rng.integers(1, 366, (10_000, 20))
bday_20 = pd.DataFrame(bday_20)
bday_20.head()

0    1    2    3    4    5    6    7    8    9    10   11   12   13   14  \
0   64  252  122   46   70   60  143  223   41  272  217   39  142  227  203   
1  318   62  290  189  285  310   26  311  307  197  331  225  281  122  115   
2  161  288  177   90  128  319  267  133  238   36  314   97  294  109  290   
3  290   75  149  334  184  277  229   39   97  178  233   51  313  130   59   
4  335  360  144  237  283  110  131  100  199  101  118  286  220  104  225   

    15   16   17   18   19  
0    8   11  204  232  313  
1  179  141  250  128  107  
2  106  268   36   54   19  
3  195  157  259  130   52  
4  365  238   79  335   76

In [38]:
share_bday_20 = (bday_20.nunique(axis=1) < 20).sum()

In [39]:
share_bday_20 / len(bday_20)

0.4144

In [40]:
bday_40 = rng.integers(1, 366, (10_000, 40))
bday_40 = pd.DataFrame(bday_40)
bday_40.head()

0    1    2    3    4    5    6    7    8    9   ...   30   31   32   33  \
0   41  153  101  191  223  311   18  139  105  222  ...  155  210  205   43   
1  105  318   80  262  276   63    1   83  192  159  ...  246   82  351  267   
2  284  365  116  270   63  282   23   21  267  157  ...  191  101  243  217   
3   55  245  325  296  146   44  174  216  104   95  ...   69  225  340    8   
4  270  142   45  250  150  152  158  274  276  106  ...  362  176   57  225   

    34   35   36   37   38   39  
0  183    6  294  220  253  315  
1  364  207  183   10   26   57  
2  248  252   75  250  296  263  
3   78   77   16   86  300  100  
4   51  167   87  139   97  116  

[5 rows x 40 columns]

In [41]:
share_bday_40 = (bday_40.nunique(axis=1) < 40).sum()

In [42]:
share_bday_40 / len(bday_40)

0.8899

# **BONUS:**

## **Mage Duel!**

**Let's use what we've learned to play a mage duel!**

**Imagine your wizard has 6d4 health points and you have spells that do 6d4 damage. "6d4" means rolling six 4-sided dice and summing the result.**

**Your opposing mage has 4d6 health points and spells that do 4d6. "4d6" means rolling four six-sided dice and summing the result.**

## **Exercises**

1. **Simulate mage duels to answer who is the more powerful mage?**

    - Before running simulations, do you have a hypothesis of which mage will win? Do you have a hunch? Write it down. This is your first exercise.*

    - Simulate 10 mage duels. Is there a clear winner? Run that 10 duel simulation again. Was the answer similar?

    - Do the results change much at 100 duels?

    - Now, simulate 10,000 mage duels. Is there a clear winner?

In [43]:
my_wiz = rng.integers(1, 5, 10).sum()
my_wiz_dmg = rng.integers(1, 5, 10).sum()

In [44]:
opps_wiz = rng.integers(1, 7, 10).sum()
opps_wiz_dmg = rng.integers(1, 7, 10).sum()

In [ ]:
sim_10_duels = 